// <auto-generated />
using System;
using ASPGTRTraining.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASPGTRTraining.DataAccess.Migrations
{
    [DbContext(typeof(ASPGTRTrainingDBContext))]
    partial class ASPGTRTrainingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASPGTRTraining.Model.Entity.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("ASPGTRTraining.Model.Entity.Designation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("Id")
                        .HasName("pk_designations");

                    b.ToTable("designations", (string)null);
                });

            modelBuilder.Entity("ASPGTRTraining.Model.Entity.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deptid");

                    b.Property<string>("DesigID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desigid");

                    b.Property<string>("DesignationId")
                        .HasColumnType("text")
                        .HasColumnName("designationid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("UpBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upby");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DeptId")
                        .HasDatabaseName("ix_employees_deptid");

                    b.HasIndex("DesignationId")
                        .HasDatabaseName("ix_employees_designationid");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("ASPGTRTraining.Model.Entity.Employee", b =>
                {
                    b.HasOne("ASPGTRTraining.Model.Entity.Department", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_deptid");

                    b.HasOne("ASPGTRTraining.Model.Entity.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .HasConstraintName("fk_employees_designations_designationid");

                    b.Navigation("Dept");

                    b.Navigation("Designation");
                });
#pragma warning restore 612, 618
        }
    }
}
